export const portfolioTypes = {
  FrontEnd: "Front-End",
  Blockchain: "Blockchain",
  FullStack: "Full-Stack",
};
export const portfolioData = [
  {
    type: portfolioTypes.FrontEnd,
    name: "HodlPad project",
    client: "HODL",
    languages: "React, JSS, Tailwindcss, Web3 integration",
    preview: "https://hodlpad.app/",
    image: "img/projects/hodlpad.png",
  },
  {
    type: portfolioTypes.FrontEnd,
    name: "Fuzzy.one project",
    client: "Fuzzy.one",
    languages: "React",
    preview: "https://fuzzy.one/",
    image: "img/projects/fuzzy.png",
  },
  {
    type: portfolioTypes.FrontEnd,
    name: "CARDENCE project",
    client: "CARDENCE",
    languages: "React, styled-components",
    preview: "https://cardence.io/",
    image: "img/projects/cardence.png",
  },
  {
    type: portfolioTypes.FrontEnd,
    name: "Akilcoin Market",
    client: "Akil",
    languages: "React, JSS",
    preview: "https://akilcoin.com/",
    image: "img/projects/akilcoin.png",
  },
  {
    type: portfolioTypes.FullStack,
    name: "Plethroi Bridge project",
    client: "Plethori",
    languages: "React, Solidity",
    preview: "https://plebridge.web.app/",
    image: "img/projects/plethori-bridge.png",
  },
  {
    type: portfolioTypes.Blockchain,
    name: "Devious Licks DGOLD",
    client: "Fitz",
    languages: "Solidity",
    preview:
      "https://bscscan.com/address/0x9e545b66afad4836656601b0a6c6c4508b33e2c4",
    image: "img/projects/devious-licks-token.png",
  },
  {
    type: portfolioTypes.FullStack,
    name: "Moon Roll",
    client: "Moon",
    languages: " React, Tailwindcss, Express, Web3 integration",
    preview: "https://moonroll.io/",
    image: "img/projects/moon-roll.png",
  },
  {
    type: portfolioTypes.FullStack,
    name: "Plethori ETF Analysis Tool",
    client: "Callum",
    languages: " React, Tailwindcss, Python",
    preview: "https://plethori-etf-analysis-tool.herokuapp.com/",
    image: "img/projects/plethori-etf.png",
  },
  {
    type: portfolioTypes.FullStack,
    name: "IMBUE",
    client: "Carrabre",
    languages: " React, Tailwindcss, Solidity, Livepeer",
    preview: "https://imbue.on.fleek.co/",
    image: "img/projects/imbue.png",
  },
  {
    type: portfolioTypes.FullStack,
    name: "Swappery",
    client: "Casper",
    languages:
      " React, Tailwindcss,Styled Component, Web3 integration, Solidity",
    preview: "https://www.the-swappery.com/",
    image: "img/projects/swappery.png",
  },
  {
    type: portfolioTypes.FullStack,
    name: "powernode",
    client: "",
    languages: "React, styled-components, Tailwindcss, Web3 integration, Node.js, AWS",
    preview: "https://powernode.io/",
    image: "img/projects/powernode.png",
  },
  {
    type: portfolioTypes.FullStack,
    name: "Swappery",
    client: "Casper",
    languages: "Typescript, Next.js, Tailwindcss, GraphQL, Strapi API",
    preview: "https://bluejestic.com/",
    image: "img/projects/bluejestic.png",
  },
  {
    type: portfolioTypes.FrontEnd,
    name: "Daclify by Animus",
    client: "-",
    languages: " Vue, Nuxt.js, SCSS",
    preview: "https://daclify.animus.is/",
    image: "img/projects/daclify.png",
  },
];
